name: servicly_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Paquetes de UI y Utilidades
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  share_plus: ^9.0.0
  video_player: ^2.8.6
  chewie: ^1.8.1
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  timeago: ^3.6.1
  font_awesome_flutter: ^10.7.0
  permission_handler: ^11.3.1
  flutter_sound: ^9.3.0
  path_provider: ^2.1.3
  url_launcher: ^6.3.0
  visibility_detector: ^0.4.0+2
  path: ^1.9.0
  intl: ^0.20.2
  photo_view: ^0.15.0
  file_picker: ^8.0.3
  timeline_tile: ^2.0.0 
  rxdart: ^0.27.7
  app_links: ^3.5.0 
  video_compress: ^3.1.2
  flutter_image_compress: ^2.3.0

  # Paquetes de Firebase
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_storage: ^11.7.4
  firebase_app_check: ^0.2.1+18
  firebase_messaging: ^14.9.1
  cloud_functions: ^4.6.1

  # Paquetes de AutenticaciÃ³n Social
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/fonts/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700

# --- Configuraciones de Paquetes ---

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/LST1024.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon/SB1024.png"

dependency_overrides:
  http: ^1.2.0